


  - name: Download Public Key for Repo
    shell: "curl -o RPM-GPG-KEY-microsoft-azure-release https://download.microsoft.com/download/9/D/9/9d945f05-541d-494f-9977-289b3ce8e774/microsoft-sign-public.asc"

  - name: Configure the public key
    shell: "sudo install -o root -g root -m 644 RPM-GPG-KEY-microsoft-azure-release /etc/pki/rpm-gpg"

  - name: Configure the public key
    shell: "sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-microsoft-azure-release"
    
  - name: Download Package version
    shell: "curl -o azureclient.rpm https://rhui-1.microsoft.com/pulp/repos/microsoft-azure-rhel7/rhui-azure-rhel7-2.1-19.noarch.rpm"
    
  - name: Install RPM
    shell: "sudo rpm -U azureclient.rpm"

  - name: install openscap scanner, ssg and httpd
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide
    - httpd

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/oscap-arf.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml
      ignore_errors: yes

    always:
    - name: Copy report for serving
      copy:
        src: /tmp/oscap-report.html
        dest: /var/www/html/index.html
        remote_src: yes
        
  - name: start httpd
    service:
      name: httpd
      state: started