# Description
# ===========
# This playbook executes the custome script on a windows host to accept WINRM connection. 
---
- name : Deploy Windows on Azure
  hosts: localhost 
  gather_facts: False
  vars: 
    vm_name: MSW2016
    resource_group: winser16
    location: australiacentral
    os_image: win
  tasks:
    - block:
      - name: set fact for Extension Code
        set_fact:
          winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=
    

      - name: create Azure vm extension to enable HTTPS WinRM listener
        azure_rm_virtualmachine_extension:
          name: winrm-extension
          resource_group: "{{ resource_group }}"
          virtual_machine_name: mswin
          publisher: Microsoft.Compute
          virtual_machine_extension_type: CustomScriptExtension
          type_handler_version: 1.9
          settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
          auto_upgrade_minor_version: true

      when: os_image == 'win'    


    - block:
      - name: No extenstion for Rhel
        debug: 
          msg: "no security script for rhel"

      when: os_image == 'rhel'    
