# Description
# ===========
# This playbook create a Windows Server VM in Azure with ports open for ssh, http(s), rdp and winrm

---
- name : Provision instance
  hosts: localhost 
  gather_facts: False

  roles:  
  - { role: cchurch.win-ec2, when: cloud_provider == 'ec2' and os_image == 'WIN'}
  - { role: azure-win, when: cloud_provider == 'azure' and os_image == 'WIN'}
  - { role: azure-rhel, when: cloud_provider == 'azure' and os_image == 'rhel'}
  - { role: ec2-rhel, when: cloud_provider == 'ec2' and os_image == 'rhel'}
