# Description
# ===========
# This playbook create a Windows Server VM in Azure with ports open for ssh, http(s), rdp and winrm

---
- name : Deploy Windows on Azure
  hosts: localhost 
  gather_facts: False
  vars: 
  roles:
    - "{{ cloud_provider }}"-"{{ os_image }}"
