# Description
# ===========
# This playbook create a Windows Server VM in Azure with ports open for ssh, http(s), rdp and winrm

---
- name : Provision Server on "{{ cloud_provider }}"
  hosts: localhost 
  gather_facts: False
  roles:
    - vsphere-rhel
