---

- name: enable repos on all instances
  hosts: tag_ansible_group
  gather_facts: false
  roles:
  - { name: ec2-3tier_repo }

- name: Install HA on frontend
  hosts: tag_Name_3Tier_Frontend
  gather_facts: false
  roles:
  - { name: ec2-3tier_haproxy }

- name: Install postgres on DB
  hosts: tag_Name_3Tier_Appdbs
  gather_facts: false
  roles:
  - { name: ec2-3tier_postgres }
 
- name: Install tomcat on Webservers
  hosts: tag_Name_3Tier_Webserver
  gather_facts: false
  roles:
  - { name: ec2-3tier_tomcat }

- name: Install tomcat on Webservers
  hosts: tag_Name_3Tier_Frontend
  gather_facts: false
  roles:
  - { name: ec2-3tier_smoke }
  tags: smoke