 - name: Azure Create virtual network
   azure_rm_virtualnetwork:
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     address_prefixes: "30.0.0.0/16"
 - name: Azure Add subnet
   azure_rm_subnet:
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     address_prefix: "30.0.1.0/24"
     virtual_network: "{{ vm_name }}"

 - name: Azure Create Network Security Group that allows SSH and HTTP Ports
   azure_rm_securitygroup:
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     purge_rules: yes
     rules:
       - name: SSH
         protocol: Tcp
         destination_port_range: 22
         access: Allow
         priority: 1001
         direction: Inbound
       - name: HTTP
         protocol: Tcp
         destination_port_range: 80
         access: Allow
         priority: 1002
         direction: Inbound
       - name: HTTPS
         protocol: Tcp
         destination_port_range: 443
         access: Allow
         priority: 1003
         direction: Inbound
 

 # Create windows
 - name: Create rhel public IP address
   azure_rm_publicipaddress:
     resource_group: "{{ resource_group }}"
     allocation_method: Static
     name: rhel

 - name: Create rhel virtual network inteface card
   azure_rm_networkinterface:
     resource_group: "{{ resource_group }}"
     name: rhel
     virtual_network: "{{ vm_name }}"
     subnet: "{{ vm_name }}"
     public_ip_name: rhel
     security_group: "{{ vm_name }}"

 - name: Azure Create rhel VM
   azure_rm_virtualmachine:
     resource_group: "{{ resource_group }}"
     name: rhel-7
     vm_size: Standard_DS1_v2
     os_type: Linux
     admin_username: az-user
     admin_password: Password@123
     network_interfaces: rhel
     tags:
       tag_ansible_group : rhel
     image:
       publisher: RedHat
       offer: RHEL
       sku: 7-RAW
       version: latest
   register: output