  - name: install tomcat
    package:
      name: httpd
      state: latest
      
  - name: enable tomcat at boot
    service:
      name: httpd
      enabled: yes

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: 0644

  - name: start tomcat
    service:
      name: httpd
      state: started
